### ISSUE TITLE
I came across the strange "Exception ignored in:"

### ISSUE THREAD

**Issue by enzoliao** [jettify/asyncio_mongo#1]
When running the examples, the python sricpt finished and ended up with ""Exception ignored in:", which has just blank after it. My py version is 3.4.3.

**Comment by jettify** [comment]
I do not recommend to use this driver, it is not supported an have a lot of bugs. Try this one https://github.com/asvetlov/motor changes from this fork will be merged to upstream  https://github.com/mongodb/motor very soon.

Regarding you question, usually this message pops up when you closing loop, right?

**Comment by enzoliao** [comment]
Thank you very much. I have turned to using Tornado and Motor. 
Yes, it pops up when I have just closed a loop. By the way, the example scripts runs smoothly without any error.

**Comment by jettify** [comment]
I may be biased, I suggest to use aiohttp + motor :). You can install it with:
```
pip install git+git://github.com/asvetlov/motor.git
```

**Comment by enzoliao** [comment]
Thanks.
